<a href="https://colab.research.google.com/github/AFDBILLIONS/Python-data-analysis-basic/blob/master/Copy_of_NumPy_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([
              [1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
#Your Code Here
print(a[1,5])

13


In [ ]:
# Get a specific row 
#Your Code Here
print(a[0,:])


[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column  ???????????
#Your Code Here

print(a[:,2])

[ 3 10]


##Array indexing
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

#Your Code Here
a=np.array([
      [1,2,3,4],
      [5,6,7,8,],
      [9,10,11,12]     
])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
#startIndex:endIndex+1
#Your Code Here
print(a[0:2,1:3])




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


##Integer array indexing: 
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
# [[1 2]
#  [3 4]
#  [5 6]]

# An example of integer array indexing.
# The returned array will have shape (3,) 

#Your Code Here
print(a[[1,2],[1,0]])


# The above example of integer array indexing is equivalent to this:
#Your Code Here
print(a[1,1], a[2,0])

[4 5]
4 5


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
#Your Code Here



# Equivalent to the previous integer array indexing example
#Your Code Here


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


####Quick background on numpy.arange
[NumPy Doc](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [ ]:
#Return evenly spaced values within a given interval
#np.arange(strat, end+1, step)
#Your Code Here
print(np.arange(3,10,2))
print(np.arange(10))
print(np.arange(3,7))

[3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]


In [ ]:
#a is:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]
# Create an array of indices
b = [0, 2, 0, 1]

# Select one element from each row of a using the indices in b
#Your Code Here
# Prints "[ 1  6  7 11]"
print(a[[0,1,2,3],b])
#a is:


[11 16 17 21]


In [ ]:
# Mutate one element from each row of a using the indices in b
#Your Code Here
a[np.arange(4),b] +=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#QUIZ!!!

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

#Your Code Here

                    # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

bool_idx=(a>2)

#Your Code Here
print(bool_idx)


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
#Your Code Here
print(a[bool_idx])

# We can do all of the above in a single concise statement:
#Your Code Here
print(a[a>2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

#QUIZ!!

##Array Math
###Recap

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#x is:            y is:
# [[1. 2.]        [[5. 6.]
# [3. 4.]]        [7. 8.]]

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
#x is:            y is:
# [[1. 2.]        [[5. 6.]
# [3. 4.]]        [7. 8.]]

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
#x is:            y is:
# [[1. 2.]        [[5. 6.]
# [3. 4.]]        [7. 8.]]

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
#x is:            y is:
# [[1. 2.]        [[5. 6.]
# [3. 4.]]        [7. 8.]]

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


##Some Additional Details about Array Math

Note that unlike MATLAB, * is elementwise multiplication, **not matrix multiplication**. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the @ operator which is equivalent to numpy's dot operator.

In [ ]:
print(v @ w)

219


In [ ]:
# x is:        v is:
#  [[1 2]      [ 9 10]
#  [3 4]]      

#v is actually a vetor
print(v.shape)

#you can visualize v like this
# [9
#  10]

#You may wonder why it's like this?
#Ans: NumPy has a concept of broadcasting and for that
#Details: https://numpy.org/doc/stable/user/basics.broadcasting.html

# Matrix / vector product; both produce the rank 1 array [29 67]??????
#Your Code Here
print(x.dot(v))
print(np.dot(x,v))
print(x@v)

(2,)
[29 67]
[29 67]
[29 67]


In [ ]:
# x is:
#  [[1 2]
#  [3 4]]

# y is:
# [[5 6]
#  [7 8]]

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
#Your Code Here
print(x@y)

[[19 22]
 [43 50]]


In Summary:

Vector*Vector ==> Scalar Product

Vectr*Matrix ==> Matrxix

Matrix*Matrix ==> Matrix

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [ ]:
x = np.array([[1,2],[3,4]])

# [[1 2]
#  [3 4]]

#Your Code Here
# Compute sum of all elements; prints "10"
print(np.sum(x))

# Compute sum of each column; prints "[4 6]"
print(np.sum(x,axis=0))

# Compute sum of each row; prints "[3 7]"
print(np.sum(x,axis=1))


10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
#Your Code Here
print(x)
print(x.T)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


This brief overview has touched on many of the important things that you need to know about numpy, but it is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

##QUIZ!!